[build]
builder = "NIXPACKS"

[build.nixpacks]
aptPkgs = ["libcanvas-dev", "libcairo2-dev", "libpango1.0-dev", "libjpeg-dev", "libgif-dev", "librsvg2-dev", "ffmpeg"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
